# This is cargo-culted from
# https://docs.travis-ci.com/user/languages/python/
# https://www.scivision.dev/travis-ci-osx-python/

language: python
jobs:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
    - name: "Homebrew Python 3 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
      addons:
        homebrew:
          packages:
          - python
      env: PATH=/usr/local/bin:${PATH}
install:
    - python3 --version
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install -r testing_requirements.txt
script:
    - flake8
    - pytest --cov=app.model
    - black --check --quiet .
