# This is cargo-culted from
# https://docs.travis-ci.com/user/languages/python/
# https://www.scivision.dev/travis-ci-osx-python/

language: python
jobs:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
    - name: "Python 3.7 on macOS"
      osx_image: xcode11
      language: shell
install:
    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install flake8 pycodestyle
script:
    - flake8
    - pytest
