# Python CircleCI configuration file
#
# See https://circleci.com/developer/orbs/orb/circleci/python
#
version: '2.1'
orbs:
  python: circleci/python@2.0.3
jobs:
  lint_and_test:
    executor: python/default
    steps:
      - checkout

      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: testing_requirements.txt
          pkg-manager: pip

      - run:
          name: lint with flake8
          command: flake8 --count --show-source --statistics one_dim_ebm.py app

      - run:
          name: Run tests
          command: python -m pytest --cov=app.model

      - run:
          name: Double-check formatting
          command: black --check --quiet one_dim_ebm.py app

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  main:
    jobs:
      - lint_and_test

